version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'some-package'
        versions: ['1.x']
